language: node_js

node_js:
  - 9

dist: trusty

sudo: required

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"