language: node_js

node_js:
  - 9

dist: trusty

sudo: required

addons:
  chrome: beta

before_install:
  - google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test
